### ISSUE TITLE
Issue following quick setup guide

### ISSUE THREAD

**Issue by jordanoverbye** [aave/lens-protocol#73]
I'm following the [quick setup guide](https://docs.lens.dev/docs/quick-setup#3-start-docker-compose) and getting the following error on step 3:

```
ERROR: Missing mandatory value for "user" option interpolating ${USERID?}:${USERID?} in service "contracts-env": USERID
```

As per the guide, I have only cloned the repo and setup a blank `.env`  file.

```
Mac OSX 12.1 (21C52) (M1)
Docker version 20.10.13, build a224086
docker-compose version 1.29.2, build 5becea4c
```

**Comment by qwolphin** [comment]
The setup was changed a bit, for now you can use setup instructions from README

https://github.com/aave/lens-protocol#setup

**Comment by jonathanng1122** [comment]
I would like to add that `EACCES: permission denied, mkdir '/.config'` error means that you do not have root access.

Instead of running: 
```
export USERID=$UID && docker-compose build && docker-compose exec contracts-env bash
```
Run the following to get root access:
```
export USERID=$UID && docker-compose build && docker-compose exec -u 0 contracts-env bash
```

If you still get mkdir errors, you want to run the following command to give write access to the path that the error says you don't have access to. You may need to `mkdir` the path also.
```
chmod 0777 <path>
```

Let me know if there is a better way to do this.

**Comment by Zer0dot** [comment]
I believe this is now outdated, feel free to re-open if the issue arises again!

**Comment by lipingx** [comment]
Running "export USERID=$UID && docker-compose build && docker-compose exec -u 0 contracts-env bash"
I got "service "contracts-env" is not running container #"

**Comment by lipingx** [comment]
Then tried "sudo mkdir /.config"
Got 
mkdir: /.config: Read-only file system 

Then
sudo chmod 0777 /.config
chmod: /.config: No such file or directory

What should I try next?

**Comment by lipingx** [comment]
Solved, see https://github.com/aave/lens-protocol/issues/134
