### ISSUE TITLE
Able to setPublicationUri

### ISSUE THREAD

**Issue by bigint** [aave/lens-protocol#78]
We can use publications other than posts and comments like e-commerce products, communities etc

Some data are intended to change like we can update the image of the community or rename the product in e-commerce product

It would be great if it is able to update the metadata uri 🙏🏻 

WDYT @Zer0dot 🙇🏻

**Comment by donosonaumczuk** [comment]
Hey @bigint! 

I see why you need it. However, that brings some trouble to the protocol as, for example, you can collect publications. And you maybe will be collecting a publication getting a collect NFT which in the future could be changed without any notice as it points to the original publication's metadata. That doesn't sound great.

You can always make your publication point to a metadata URI which content its upgradeable, like using a link to your own server, but I understand that you would like to use IPFS or something like that.

The only path I see for adding this feature is by also adding a way to lock/freeze the metadata. So you can't call `setPublicationURI` successfully if you already frozen the metadata, bringing back the notion of immutability which is needed for most of the cases. So it could look like this:

```solidity
setPublicationURI(uint256 profileId, uint256 pubId, string calldata uri, bool freezed)

freezePublicationURI(uint256 profileId, uint256 pubId)
```

But UIs should be very clear about this, otherwise people will be collecting things that can change in the future without noticing it.

Looking forward for @oneski and @Zer0dot thoughts here.

**Comment by Zer0dot** [comment]
I don't think this is a contract layer change, I agree that if you're using Lens as an eCom store layer, you're probably running your own server anyway, and the trust assumptions are there that you'll deliver on your promises-- so I think it's best to use your own server with editable metadata URIs.

**Comment by Zer0dot** [comment]
Going to close this for now, but keep the subject fresh in your mind @bigint, there is a lot of potential for future development!
